export const nav = {
  links: [
    { label: "Portfolio", href: "/portfolio" },
    { label: "Offering", href: "/offering" },
    { label: "About", href: "/about" },
    { label: "Blog", href: "/blog" },
  ],
  cta: { label: "Start a conversation", href: "/contact" },
};

// All real clients & portfolio companies for the ticker
export const ticker = [
  "WiseMize", "Vyve", "Volumio", "Solintegra", "Matherials", "MOD INC.", "Venture Builder AI",
  "SiriNor", "Lissen", "AI:OK", "Digit Music", "Allfeat", "Blizbi", "Thor Kraft",
  "Unlisted AI", "Tuned Global", "AIDAR", "Unitesync", "Bandbeat", "Hopcast",
  "Vekstpartner", "unhurd music", "SpareBank 1", "Music Estonia", "Capella Norway",
  "Instorier", "LongformAI", "PaleBlue", "WARM", "Sera",
  // Duplicated for seamless loop
  "WiseMize", "Vyve", "Volumio", "Solintegra", "Matherials", "MOD INC.", "Venture Builder AI",
  "SiriNor", "Lissen", "AI:OK", "Digit Music", "Allfeat", "Blizbi", "Thor Kraft",
  "Unlisted AI", "Tuned Global", "AIDAR", "Unitesync", "Bandbeat", "Hopcast",
  "Vekstpartner", "unhurd music", "SpareBank 1", "Music Estonia", "Capella Norway",
  "Instorier", "LongformAI", "PaleBlue", "WARM", "Sera",
];

export const hero = {
  eyebrow: "Venture Studio",
  lineOne: "Zero",
  lineTwo: "To Investor-",
  lineThree: "Ready.",
  sub: "We co-build with founders from first idea to investor-ready company — technology, market validation, and investor storytelling. No deck required to start.",
};

// Stats — all values are verifiable from portfolio and team data
export const stats: { number: string; suffix: string; prefix?: string; label: string }[] = [
  { number: "40", suffix: "+", label: "Ventures supported" },
  { number: "70", suffix: "+", label: "Team members globally" },
  { number: "6", suffix: "×", label: "Portfolio exits" },
];

export const whoWeWorkWith = [
  {
    num: "01",
    title: "Idea-stage founders",
    body: "You have a clear insight but no company yet. We validate direction and move from concept to product — before you burn runway on the wrong thing.",
    tag: "Zero to one",
  },
  {
    num: "02",
    title: "Pre-seed teams",
    body: "You've built something but need sharper execution, a stronger story, or real momentum toward your first institutional round.",
    tag: "Pre-seed",
  },
  {
    num: "03",
    title: "Founders at inflection",
    body: "You're stalled, pivoting, or facing hard decisions about focus and growth. We bring clarity and hands-on execution — not just advice.",
    tag: "Growth stage",
  },
  {
    num: "04",
    title: "European founders, global build",
    body: "You're building in Europe but need global reach. Distributed execution without the chaos of hiring a remote team from scratch.",
    tag: "Global",
  },
];

export const services = [
  {
    id: "capital",
    title: "Co-build",
    headline: "Technology that works.",
    body: "AI agents, functional MVPs, full platform builds, and production-ready codebases — delivered in 6–20 weeks. We stay close to execution, not just oversight.",
    detail: "Web, mobile, and AI across any stack. We co-build and co-own — not an agency.",
  },
  {
    id: "build",
    title: "Validate",
    headline: "Know before you build.",
    body: "Market sizing, competitor mapping, and go/no-go feasibility analysis. We pressure-test the idea before writing a line of code. Research-backed clarity in weeks, not months.",
    detail: "Clear frameworks so you build what the market actually needs.",
  },
  {
    id: "raise",
    title: "Raise",
    headline: "Investor-ready.",
    body: "Pitch decks, one-pagers, investor targeting, outreach messaging, and data room structure. We've helped founders contact 100+ investors with 10–40% response rates.",
    detail: "Fundraising strategy, not just slides. Story that closes rounds.",
  },
];

// Five principles from AV copy direction document
export const principles = [
  {
    num: "01",
    title: "We push for what works",
    body: "We challenge assumptions early and push back when focus drifts. No politeness — just honest direction toward what actually moves the needle.",
  },
  {
    num: "02",
    title: "We do the heavy lifting",
    body: "We stay close to execution and carry projects through ambiguity. Not a board seat — an embedded co-builder from day one.",
  },
  {
    num: "03",
    title: "Progress over politeness",
    body: "Clarity, accountability, delivery — in that order. We call problems early and keep communication honest, even when it's uncomfortable.",
  },
  {
    num: "04",
    title: "Direct and transparent",
    body: "No smoke, no spin. We tell you what we see — the opportunity and the risk — and we expect the same in return.",
  },
  {
    num: "05",
    title: "We build for durability",
    body: "We optimise for companies that hold up over time — not quick outcomes. Investor-ready traction that founders can stand behind and defend.",
  },
];

// Real testimonials — confirmed names and quotes from source documents
export const testimonials = [
  {
    quote: "Working with Amplitude was a game changer for us. They helped us get the clarity we needed on our unique value and vision when pivoting our business and supported us in perfecting our new pitch.",
    name: "Joseph Pinho",
    role: "Co-founder",
    co: "MOD INC.",
  },
  {
    quote: "The most valuable aspects of our partnership have been the rapid development of an MVP and the swift establishment of a pipeline of interested customers — two critical pillars in our journey towards achieving product-market fit.",
    name: "Kunal Karadia",
    role: "Co-founder",
    co: "Venture Builder AI",
  },
  {
    quote: "I would recommend Jakob and the Amplitude team without hesitation to any founder or startup looking for a development partner that combines top-tier technical skills with heart, transparency, and real partnership.",
    name: "Helene Birkeland",
    role: "Founding CEO",
    co: "HappyNova / Blizbi",
  },
  {
    quote: "It is impressive to get to know the expertise Amplitude Venture has in AI, as well as how targeted and quickly they work.",
    name: "Atle Riskedal",
    role: "Business Developer",
    co: "Vekstpartner",
  },
];

// Real blog articles from Framer CMS (collection MJaXEj6bi)
export const blogPosts = [
  {
    slug: "why-music-tech-startups-starve-while-billions-flow-to-the-top-and-how-we-re-solving-it",
    category: "Article",
    title: "Why Music Tech Startups STARVE while Billions Flow to the Top — and How We're Solving It",
    excerpt: "The music industry holds vast amounts of capital. Yet almost every founder building music tech struggles to access it. Based on 2-year research, 110+ podcast episodes analyzed, 30+ founders interviewed.",
    date: "2025-07-04",
    readTime: "8 min",
    thumbnail: "https://framerusercontent.com/images/eAxkTWiI4YXOrlHBThYcXuGvYaM.png",
    body: [
      "The music industry holds vast amounts of capital. Yet almost every founder building music tech struggles to access it. Based on 2-year research, a Master's thesis at University of Agder, 110+ podcast episodes analyzed, and 30+ founders interviewed — we've mapped exactly why this happens and what to do about it.",
      "Most music tech startups fail to raise not because their ideas are weak, but because they pitch into the wrong frame. Investors who don't understand music see a niche. Investors who do understand music see a ceiling. The problem is narrative, not product.",
      "We developed the \"Parallel Narratives\" framework to solve this: build two simultaneous stories for your company — one for music-native investors, one for generalist investors. The same traction, the same product, framed entirely differently. It's not spin. It's translation.",
      "The founders who crack funding in music tech aren't the ones with the best products. They're the ones who've learned to speak the language of capital — while staying true to what they're actually building.",
    ],
  },
  {
    slug: "from-survival-to-scale-how-we-built-a-profitable-venture-studio-of-70-in-10-months",
    category: "Article",
    title: "From Survival to Scale: How We Built a Profitable Venture Studio of 70+ in 10 Months",
    excerpt: "From 2 people nearly out of runway in March 2024 to 70+ global team in 10 months. The exact decisions that built a dual-engine venture studio.",
    date: "2025-06-19",
    readTime: "6 min",
    thumbnail: "https://framerusercontent.com/images/ZXxZ2M58OzW033BYq1Wxa9GTyuQ.png",
    body: [
      "In March 2024, Amplitude Ventures was two people with six weeks of runway. By January 2025, we had 70+ team members across Europe, Africa, and Asia and were operating profitably. This is the exact story of how that happened.",
      "The critical decision was building a dual-engine model: paid service work (which generates immediate revenue) running in parallel with co-building ventures (which builds long-term equity value). Neither alone would have worked. Together, they created a self-sustaining flywheel.",
      "We hired distributed teams from Ethiopia, Nigeria, Malawi, and Burundi — not as a cost play, but because extraordinary talent exists in places most studios aren't looking. That decision shaped everything about how we work and what we're able to build.",
      "The hard part wasn't the hiring. It was building the operating system: how to run 12 active ventures simultaneously, how to maintain quality across time zones, how to keep founders confident in a team they've never met in person. That system is what we're sharing here.",
    ],
  },
  {
    slug: "music-tech-financing-part-3-the-investor-s-narrative",
    category: "Article",
    title: "Music Tech Financing – Part 3: The Investor's Narrative",
    excerpt: "Why 75% of music tech exits are under $15M — and how to position your startup for the investors who break that pattern.",
    date: "2025-06-10",
    readTime: "5 min",
    thumbnail: "https://framerusercontent.com/images/fnyuZP734VVCZFW2upyAqLG4mY.jpg",
    body: [
      "Seventy-five percent of music tech exits are under $15M. That single statistic explains almost everything about why VCs don't fund music tech at scale — and it gives you the playbook for what to do about it.",
      "The investors who do fund music tech are almost never music-native. They're generalists who see a large market adjacent to something they already understand: consumer behavior, B2B SaaS, platform network effects. Your job is to help them see your company through that lens.",
      "This isn't about hiding what you are. It's about surfacing the part of your story that maps to patterns investors have already backed. A music royalty platform isn't just a music company — it's a financial data infrastructure play. A music creation tool isn't just music software — it's a creator economy platform.",
      "Part 3 of our Music Tech Financing series goes deep on constructing the investor narrative: which frame to lead with, which metrics to feature, and how to answer the inevitable question about exit comparables.",
    ],
  },
  {
    slug: "the-future-of-music-creation-a-prediction",
    category: "Article",
    title: "The Future of Music Creation – A Prediction",
    excerpt: "AI is already changing how we make music. Seven predictions for where it goes next — and what it means for founders building in this space.",
    date: "2025-06-01",
    readTime: "7 min",
    thumbnail: "https://framerusercontent.com/images/vdhrdrLyw4iHtB1GDMIrTJPMbA.png",
    body: [
      "Music is about to change in ways we couldn't imagine five years ago. AI is already reshaping how music gets made — but we're still in the first inning. The real disruption is ahead.",
      "Seven pillars will define the next decade of music creation: democratization (anyone can create), ideas as the new currency (execution becomes trivially cheap), redefinition of creativity (what does authorship mean?), content explosion (more music than anyone can consume), human-AI collaboration (the most interesting new instrument), human connection (the thing AI cannot replace), and ethical frameworks (who owns what, and who profits).",
      "The founders who build in this space right now are making bets on which of these pillars matter most. The ones who get it right will build the infrastructure of the next music industry — not the one that exists today.",
      "This is our full prediction for how music creation evolves, and what it means for the entrepreneurs, investors, and artists trying to navigate it.",
    ],
  },
  {
    slug: "music-tech-founders-you-are-wasting-time-chasing-investors",
    category: "Article",
    title: "Music Tech Founders: You Are Wasting Time Chasing Investors",
    excerpt: "In the fast-paced world of music tech, time is your most valuable asset. Here's what to change before your next fundraise.",
    date: "2025-06-05",
    readTime: "5 min",
    thumbnail: "https://framerusercontent.com/images/mOXbFbqRYECMlTpJ9EgSOsR0FUk.jpg",
    body: [
      "Most music tech founders spend 60-70% of their fundraising time talking to the wrong investors — people who will never write a cheque for a music company, no matter how good the pitch.",
      "The fix is the Parallel Narratives concept: instead of pitching your company as a music startup, pitch it as a [category] company that happens to operate in music. The exact same traction, presented in the frame that matches the investor's existing thesis.",
      "This isn't dishonest. It's accurate — most music tech companies serve markets that generalist investors understand perfectly well. They just don't see it yet because you're leading with the word 'music' before you've established the market size and the mechanism.",
      "Stop chasing music-specific investors who have seen a hundred pitches and have been burned by the exit statistics. Start finding generalist investors whose thesis your company fits. The conversation is completely different.",
    ],
  },
  {
    slug: "navigating-the-music-tech-investment-landscape-part-1",
    category: "Article",
    title: "Navigating the Music Tech Investment Landscape – Part 1",
    excerpt: "How do you raise money for a music tech startup in a complex, misunderstood industry? Part 1 of our deep-dive series.",
    date: "2025-06-06",
    readTime: "6 min",
    thumbnail: "https://framerusercontent.com/images/vMiiJskQgWpgWWMXrWUJcG0xgQ.png",
    body: [
      "Raising for a music tech startup is harder than raising for almost any other category. The market is real, the opportunity is large, but the pattern-matching that drives most VC decisions works against you by default.",
      "Part 1 of our series covers the structural dynamics: why behavioral finance in investment decisions disadvantages music tech, how the Parallel Narratives framework was formally defined, and what ecosystem integration strategy means in practice.",
      "The founders who've cracked this aren't smarter or luckier. They've developed a systematic approach to investor selection and narrative framing that gives them an unfair advantage in rooms where music usually loses.",
      "This is the first of three parts. By the end, you'll have a complete framework for approaching music tech fundraising in a way that actually works.",
    ],
  },
  {
    slug: "suno-and-udio-have-been-sued-maybe-i-will-as-well",
    category: "Article",
    title: "Suno and Udio Have Been Sued. Maybe I Will Be As Well.",
    excerpt: "Norway's first AI-generated russemusikk business. 3,000 songs created with Suno. What happens when you build at the edge of copyright law?",
    date: "2025-05-29",
    readTime: "7 min",
    thumbnail: "https://framerusercontent.com/images/Rgc2nLeF11SHZ9eCQt4bFP69zo.jpg",
    body: [
      "When Suno and Udio were sued by the major labels, I realized I was probably next. I had spent the previous months building Norway's first viable AI-generated russemusikk business under the AI artist name 'Backstreet' — and we had already created over 3,000 songs.",
      "The legal questions around AI music are genuinely unsettled. Who owns the output of an AI trained on copyrighted music? What counts as infringement when no human wrote the melody? These aren't rhetorical questions — they're live litigation, and the answers will shape an entire industry.",
      "But here's what I think gets missed in the coverage: the ethical questions matter more than the legal ones. Even if AI-generated music is eventually ruled legal, the question of whether it's right — whether it respects the artists whose work trained the model — doesn't go away.",
      "This post is my attempt to think through where I stand on ethical AI music creation, what guardrails I've put in place for my own work, and why I think the founders building in this space need to take these questions seriously before regulators force them to.",
    ],
  },
];

// ── Inner page content ────────────────────────────────────────────────────────

// All real portfolio companies from Framer CMS
// type: "Company" = co-built / strategic partner | "Project" = AV internal | "Client" = service engagement
export const portfolioCompanies: {
  name: string;
  tagline: string;
  stage?: string;
  year: string;
  category: string;
  type: "Company" | "Project" | "Client";
  url?: string;
  role?: string;
}[] = [
  // ── Companies (co-built / strategic partner) ──────────────────────────────
  {
    name: "WizeMice",
    tagline: "Music tech platform. Slush Music Accelerator winner. Backed by SoundHub and Wave Lab.",
    stage: "Seed",
    year: "2024",
    category: "Music Tech",
    type: "Company",
    url: "https://wizemice.com/",
    role: "Market Research / Define Investor ICPs / Execute Investor Outreach Campaigns",
  },
  {
    name: "SiriNor",
    tagline: "Zero-emission jet engine technology. Deep-tech energy meets aerospace.",
    stage: "Pre-seed",
    year: "2024",
    category: "CleanTech",
    type: "Company",
    url: "https://www.sirinor.com/",
  },
  {
    name: "Lissen",
    tagline: "Next-generation music streaming platform built for artist-fan connection.",
    stage: "Pre-seed",
    year: "2024",
    category: "Music Tech",
    type: "Company",
  },
  {
    name: "MOD",
    tagline: "Fan art licensing platform. Business pivot support, value proposition clarity, and pitch refinement.",
    stage: "Pre-seed",
    year: "2024",
    category: "Creative Industries",
    type: "Company",
  },
  {
    name: "AI:OK",
    tagline: "Ethical AI music creation. Responsible AI tools for artists and rights holders.",
    stage: "Pre-seed",
    year: "2024",
    category: "Music Tech / AI",
    type: "Company",
    url: "https://ai-ok.org/",
    role: "Develop pitch deck, data room, and investor strategy / Enhance communication strategies",
  },
  {
    name: "Digit Music",
    tagline: "Music education technology. Making music learning accessible and scalable.",
    stage: "Pre-seed",
    year: "2024",
    category: "EdTech",
    type: "Company",
    url: "https://www.digitmusic.co.uk/",
    role: "Develop Product Features / Build Strategic Storytelling, Pitch Decks, and Investor Capital Strategy",
  },
  {
    name: "Allfeat",
    tagline: "Blockchain-based music metadata infrastructure. Royalty transparency at scale.",
    stage: "Pre-seed",
    year: "2023",
    category: "Music Tech / Web3",
    type: "Company",
    role: "Conduct Market Research / Build Pitch Deck, Data Room, and Investor strategy",
  },
  {
    name: "Vyve",
    tagline: "AI sustainability platform. Idea to live product in 3 months. Active user pipeline.",
    stage: "Pre-seed",
    year: "2024",
    category: "AI / Sustainability",
    type: "Company",
    role: "Investing as an Early-Stage Strategic Partner / Provide Full-Stack Tech Development / Lead Website Storytelling, Brand Messaging, and Social Media / Develop ICP, One-Pagers",
  },
  {
    name: "Blizbi",
    tagline: "Activity discovery platform. MVP built, customer acquisition underway.",
    stage: "Pre-seed",
    year: "2024",
    category: "Consumer Tech",
    type: "Company",
    role: "Develop the full MVP Platform / Conduct Market Research and Create Storytelling and Pitch Deck / Provide Ongoing Operational Support",
  },
  {
    name: "The Blues Project",
    tagline: "Soul and R&B platform connecting artists with audiences and opportunities.",
    stage: "Pre-seed",
    year: "2024",
    category: "Music Tech",
    type: "Company",
    url: "https://thebluesproject.co/",
    role: "Develop MVP for the B2C platform / Design UI/UX, Build Backend Architecture, and Payment Integration",
  },
  {
    name: "Thor Kraft",
    tagline: "Nuclear energy startup. Clean, scalable power for a post-fossil world.",
    stage: "Pre-seed",
    year: "2024",
    category: "Energy",
    type: "Company",
    url: "https://thor-kraft.no/",
    role: "Pitch Deck, Data Rooms, and Investor Strategy",
  },
  {
    name: "Unlisted AI",
    tagline: "Cap table management platform with AI-driven investor relations and compliance.",
    stage: "Pre-seed",
    year: "2024",
    category: "FinTech / AI",
    type: "Company",
    url: "https://en.unlisted.ai/",
  },
  {
    name: "Altech AS",
    tagline: "Valve distribution and industrial supply chain. Technology-enabled B2B operations.",
    stage: "Growth",
    year: "2023",
    category: "Industrial Tech",
    type: "Company",
  },
  {
    name: "Tuned Global",
    tagline: "B2B music streaming infrastructure. White-label platform for telcos and brands.",
    stage: "Growth",
    year: "2023",
    category: "Music Tech",
    type: "Company",
    url: "https://www.tunedglobal.com/",
  },
  {
    name: "AIDAR",
    tagline: "AI-powered artist scouting. Identify emerging talent before the market does.",
    stage: "Pre-seed",
    year: "2024",
    category: "Music Tech / AI",
    type: "Company",
    url: "https://www.aidar.ai/",
  },
  {
    name: "Unitesync",
    tagline: "Royalty recovery platform. Helping artists and rights holders reclaim what's owed.",
    stage: "Pre-seed",
    year: "2024",
    category: "Music Tech",
    type: "Company",
    url: "https://www.unitesync.com/",
    role: "End-to-End Platform Development Service",
  },
  {
    name: "Music Tech Europe Academy",
    tagline: "Education and acceleration for the next generation of music tech founders.",
    stage: "Seed",
    year: "2023",
    category: "EdTech / Music",
    type: "Company",
    url: "https://www.musictecheuropeacademy.eu/",
  },
  {
    name: "Advochord",
    tagline: "Music technology and advocacy platform.",
    year: "2024",
    category: "Music Tech",
    type: "Company",
  },
  {
    name: "Mantik Music Norway",
    tagline: "Norwegian music platform for discovery and artist development.",
    year: "2024",
    category: "Music Tech",
    type: "Company",
  },
  {
    name: "Russelåter.no",
    tagline: "Digital platform preserving and celebrating Norwegian graduation music traditions.",
    year: "2024",
    category: "Music / Culture",
    type: "Company",
  },
  {
    name: "Mintix",
    tagline: "Next-generation ticketing platform for live events.",
    year: "2024",
    category: "Events Tech",
    type: "Company",
  },

  // ── Projects (AV-owned / internal) ────────────────────────────────────────
  {
    name: "Venture Builder AI",
    tagline: "AI-driven venture building platform. MVP built and customer pipeline established.",
    year: "2024",
    category: "AI / SaaS",
    type: "Project",
    role: "Co-found and co-own the Company / Provide end to end platform development service",
  },
  {
    name: "Sera",
    tagline: "Remote work coordination platform. Building the future of distributed teams.",
    year: "2024",
    category: "Future of Work",
    type: "Project",
    role: "Found and Operate the Company / Manage End-to-End Development",
  },
  {
    name: "AI Dev Club",
    tagline: "Community platform for AI developers in Scandinavia. Workshops, network, resources.",
    year: "2024",
    category: "Community",
    type: "Project",
    role: "Found and Operate the Company / Manage End-to-End Development",
  },
  {
    name: "Sound Connections Podcast",
    tagline: "110+ episodes. The go-to podcast for music tech founders and investors.",
    year: "2023",
    category: "Media",
    type: "Project",
  },
  {
    name: "Capella Norway",
    tagline: "Digital choir platform. Building community through collaborative music creation.",
    year: "2024",
    category: "Music Tech",
    type: "Project",
  },
  {
    name: "Molly og Mi",
    tagline: "Norwegian family music brand. Social media, music production, and platform development.",
    year: "2024",
    category: "Music / Entertainment",
    type: "Project",
    url: "https://mollyogmi.no/",
    role: "Co-own and Cooperate / Manage Social Media / Handle Music Production / Conduct Market Research / Develop Website",
  },

  // ── Clients (service engagements) ─────────────────────────────────────────
  {
    name: "Volumio",
    tagline: "Near break-even acquisition. Product development and growth support.",
    stage: "Growth",
    year: "2023",
    category: "Music Tech",
    type: "Client",
    url: "https://volumio.com/",
    role: "Define Targeted Profiles / Develop Sales Presentation Materials / Run Outreach Campaigns",
  },
  {
    name: "Solintegra",
    tagline: "100+ investors contacted. 10–40% response rate on investor outreach.",
    stage: "Pre-seed",
    year: "2024",
    category: "Energy",
    type: "Client",
    url: "https://www.solintegra.no/",
    role: "Support Investor Outreach / Manage Platform Stability / Conduct Lead Research",
  },
  {
    name: "Matherials",
    tagline: "Suitcase Whiteboard — portable education hardware with global market potential.",
    stage: "Pre-seed",
    year: "2023",
    category: "EdTech",
    type: "Client",
    url: "https://matherials.no/",
    role: "Define ICP / Develop Tailored Messaging Framework / Set Up Outreach Tracking",
  },
  {
    name: "Instorier",
    tagline: "Interactive storytelling platform. MVP built and early user validation complete.",
    year: "2024",
    category: "Consumer Tech",
    type: "Client",
    url: "https://instorier.com/",
    role: "Conduct Lead Identification / Design CRM-ready Systems / Develop Outreach Templates",
  },
  {
    name: "LongformAI",
    tagline: "AI-powered long-form content creation. Product strategy and GTM support.",
    year: "2024",
    category: "AI / SaaS",
    type: "Client",
    url: "https://longform.ai/",
    role: "Develop Investor Pitch Deck / Build CRM System / Support Investor Outreach",
  },
  {
    name: "Bandbeat",
    tagline: "Band collaboration and rehearsal platform. Product development from concept.",
    year: "2024",
    category: "Music Tech",
    type: "Client",
    url: "https://www.bandbeat.com/",
    role: "Map Customer Segments / Develop Outreach Messaging and Run Campaigns",
  },
  {
    name: "Hopcast",
    tagline: "Live events and venue discovery platform. Full product build and launch.",
    year: "2024",
    category: "Events Tech",
    type: "Client",
    url: "https://www.hopcast.fr/",
    role: "Market Research / Define Investor Profiles / Craft Outreach Messaging",
  },
  {
    name: "Vekstpartner",
    tagline: "Business development and AI strategy. Partnership and growth consulting.",
    year: "2024",
    category: "Business Services",
    type: "Client",
    url: "https://www.vekstpartner.no/",
  },
  {
    name: "unhurd music",
    tagline: "Music distribution and artist growth. Product and marketing strategy.",
    year: "2024",
    category: "Music Tech",
    type: "Client",
    url: "https://www.unhurdmusic.com/",
  },
  {
    name: "SpareBank 1",
    tagline: "AI strategy and innovation consulting for Norway's leading regional bank.",
    year: "2024",
    category: "FinTech",
    type: "Client",
  },
  {
    name: "Music Estonia",
    tagline: "National music export strategy. Digital platform and international reach.",
    year: "2024",
    category: "Music / Policy",
    type: "Client",
    url: "https://www.musicestonia.eu/en",
  },
  {
    name: "PaleBlue",
    tagline: "Sustainable packaging technology. Investor readiness and pitch preparation.",
    year: "2024",
    category: "CleanTech",
    type: "Client",
    url: "https://pale.blue/",
    role: "Develop B2B Marketing Strategy / Conduct Market Analysis / Enrich Lead Data",
  },
  {
    name: "WARM",
    tagline: "Wellness and mindfulness platform. MVP and early traction strategy.",
    year: "2024",
    category: "Health Tech",
    type: "Client",
    url: "https://www.warmmusic.net/",
    role: "Modernize Web Application / Conduct Lead Research / Manage Outreach to Partners",
  },
  {
    name: "University of Stavanger",
    tagline: "AI in education research partnership. Applied AI tools for higher education.",
    year: "2024",
    category: "EdTech",
    type: "Client",
    url: "https://www.uis.no/en",
  },
  {
    name: "Oracles of Norway",
    tagline: "Cultural storytelling platform. Digital product and brand identity.",
    year: "2024",
    category: "Culture / Media",
    type: "Client",
    url: "https://www.oraclesofnorway.com/",
    role: "Digital Marketing Strategy / Develop End-to-End AI-Powered Mobile Platform",
  },
  {
    name: "Music Frontiers",
    tagline: "International music accelerator. Program design and founder support.",
    year: "2024",
    category: "Music Tech",
    type: "Client",
    url: "https://musicfrontiers.com/",
    role: "Co-organize and manage accelerator program / Manage Participant outreach, mentorship, event promotion",
  },
  {
    name: "Temple Studios",
    tagline: "Creative studio and production house. Business development and partnerships.",
    year: "2024",
    category: "Creative Industries",
    type: "Client",
    url: "https://www.templestudios.be/",
  },
  {
    name: "Family in Music",
    tagline: "Music education for families. Product development and community building.",
    year: "2024",
    category: "EdTech / Music",
    type: "Client",
    url: "https://familyinmusic.com/",
  },
  {
    name: "Get Moments",
    tagline: "Activity and experience discovery platform for event organizers.",
    year: "2024",
    category: "Events Tech",
    type: "Client",
    url: "https://organizer.getmoments.com/",
    role: "Define ICPs / Run Targeted Outreach / Develop Sales Playbook",
  },
  {
    name: "StreamPush",
    tagline: "Streaming and content delivery technology for media companies.",
    year: "2024",
    category: "Media Tech",
    type: "Client",
    url: "https://streampush.co/",
    role: "Lead Identification, Data Enrichment, and Prospect Qualification / Run Outreach Campaigns",
  },
  {
    name: "Sambach",
    tagline: "Creative arts platform connecting artists with collectors and fans.",
    year: "2024",
    category: "Creative Industries",
    type: "Client",
    url: "https://sambach.art/",
    role: "Lead and Prospect Identification / Manage Outreach Campaigns",
  },
  {
    name: "Music Tech at Slush",
    tagline: "The leading music tech stage at Slush, Europe's top startup conference.",
    year: "2024",
    category: "Music Tech",
    type: "Client",
    url: "https://www.musictech.live/",
  },
];

export const about = {
  eyebrow: "Our story",
  headline: "We build\ncompanies.",
  subheadline: "Then we help raise.",
  story: [
    "Amplitude Ventures is a venture studio based in Stavanger, Norway. We partner with founders as early-stage co-builders — taking on the heavy lifting of product development, market validation, and investor storytelling.",
    "Our thesis is simple: most early-stage companies don't fail because they can't raise. They fail because they can't execute to the point where raising makes sense. We close the execution gap.",
    "With 70+ team members across Europe, Africa, and Asia, we build technology, run research, create investor narratives, and embed talent — so founders can move from zero to investor-ready without compromising speed or quality.",
    "Every engagement begins with deep collaborative due diligence — stress-testing assumptions, mapping the competitive landscape, and aligning on what success looks like. In select cases, where the thesis and timing align, we also take an equity position as an early-stage strategic partner.",
  ],
  pullQuote:
    "We effectively operate as your early-stage co-founder. We're not here to maximise billings — we're here to build sustainable, investor-ready businesses alongside you.",
  pullQuoteAuthor: "Amplitude Ventures",
  team: [] as { name: string; role: string; background: string; focus: string }[],
};

export const contact = {
  headline: "Let's talk.",
  sub: "Building something and need a co-builder? We want to hear it — no deck required.",
  email: "hello@amplitudeventures.vc",
  linkedin: "linkedin.com/company/amplitude-ventures",
};
